#!/usr/bin/env python3
# ============================================================================
# Figure generation for the LOPO eye-movement classification study
# ============================================================================
# Produces the publication figures (300 DPI, MDPI style: white background,
# bottom panel labels, no super-title). File names follow the manuscript:
#
#   Figure01.png  - dataset overview            (paper Figure 1)
#   Figure02.png  - model architecture          (paper Figure 3)
#   Figure04.png  - confusion matrix            (paper Figure 4)
#   Figure05.png  - training dynamics           (paper Figure 5)
#   Figure06.png  - ablation study              (paper Figure 6)
#   Figure07.png  - per-fold distribution       (paper Figure 7)
#
# Note: the label-generation schematic (paper Figure 2, Figure03.png) was
# produced separately as a vector graphic and is not generated by this script.
#
# Data sources:
#   - Figure01 reads fig1_person_distribution.csv and fig1_sigma_distribution.csv
#   - Figure05 reads fig4_training_history.csv
#   These are produced by lopo_experiment.py / training_history.py (see RESULTS).
#   The confusion matrix and per-fold accuracies below are the values produced
#   by the 15-fold LOPO run (lopo_fold_results.csv).
# ============================================================================

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import numpy as np
import pandas as pd
from pathlib import Path

# Directories. RESULTS holds the CSVs; OUT receives the figures.
RESULTS = Path('results')
OUT     = Path('figures')
OUT.mkdir(parents=True, exist_ok=True)

BASE_RC = {
    'figure.facecolor': 'white', 'axes.facecolor': 'white',
    'savefig.facecolor': 'white', 'axes.edgecolor': 'black',
    'axes.grid': True, 'grid.color': '#cccccc', 'grid.linewidth': 0.6,
    'grid.alpha': 0.5, 'font.family': 'DejaVu Sans',
}

# Class colors, consistent across figures.
C_FIX, C_SAC, C_SP = '#E67E22', '#C0392B', '#3498DB'
# Model colors, consistent across figures.
C_MODEL = ['#E67E22', '#3498DB', '#27AE60']  # CNN, LSTM, CNN+LSTM

# ----------------------------------------------------------------------------
# Data loaders. All figure values are read from the outputs of
# lopo_experiment.py rather than being hard-coded, so the figures always
# reflect the actual experiment results.
#   - lopo_fold_results.csv : per-fold accuracies (columns acc_CNN, acc_LSTM,
#                             acc_CNN+LSTM; one row per held-out participant)
#   - yt_all.npy, hyb_all.npy : pooled true labels and CNN+LSTM predictions
# ----------------------------------------------------------------------------
def load_fold_results():
    """Return (persons, acc_cnn, acc_lstm, acc_hyb) from lopo_fold_results.csv,
    ordered by participant id (p00..p14)."""
    df = pd.read_csv(RESULTS / 'lopo_fold_results.csv')
    df = df.sort_values('test_person').reset_index(drop=True)
    persons = df['test_person'].tolist()
    return (persons,
            df['acc_CNN'].values * 100.0,
            df['acc_LSTM'].values * 100.0,
            df['acc_CNN+LSTM'].values * 100.0)

def load_confusion():
    """Compute the aggregated CNN+LSTM confusion matrix from the pooled
    predictions saved by lopo_experiment.py (yt_all.npy, hyb_all.npy).
    Rows = true (Fixation, Saccade, Smooth Pursuit), columns = predicted."""
    from sklearn.metrics import confusion_matrix
    yt  = np.load(RESULTS / 'yt_all.npy')
    hyb = np.load(RESULTS / 'hyb_all.npy')
    return confusion_matrix(yt, hyb)

def _save(fig_stem, png_only=False):
    exts = [('png', dict(dpi=300))] if png_only else \
           [('png', dict(dpi=300)), ('pdf', dict()), ('tiff', dict(dpi=300))]
    for ext, kw in exts:
        path = OUT / f'{fig_stem}.{ext}'
        plt.savefig(path, bbox_inches='tight', facecolor='white', **kw)
        print(f'  saved {path}')


# ============================================================================
# Figure 1 (Figure01.png): dataset overview, four panels
# ============================================================================
def make_figure01():
    plt.rcParams.update(BASE_RC)
    dfp = pd.read_csv(RESULTS / 'fig1_person_distribution.csv')
    dfs = pd.read_csv(RESULTS / 'fig1_sigma_distribution.csv')

    fig, axes = plt.subplots(2, 2, figsize=(14, 11))
    ax_a, ax_b, ax_c, ax_d = axes[0,0], axes[0,1], axes[1,0], axes[1,1]

    # (a) class distribution pie
    sizes = [110126, 53009, 50373]  # SP, Fixation, Saccade
    labels = ['Smooth Pursuit\n51.6%', 'Fixation\n24.8%', 'Saccade\n23.6%']
    ax_a.pie(sizes, labels=labels, colors=[C_SP, C_FIX, C_SAC],
             startangle=90, counterclock=False,
             wedgeprops=dict(edgecolor='black', linewidth=1.5),
             textprops=dict(fontsize=11, fontweight='bold'))
    ax_a.set_aspect('equal'); ax_a.grid(False)
    ax_a.text(0, -1.35, 'n = 213,508 sequences', ha='center', fontsize=10, style='italic')

    # (b) sequences per participant (LOPO fold sizes)
    persons = dfp['person'].values
    nseq = dfp['n_seq'].values
    xpos = np.arange(len(persons))
    ax_b.bar(xpos, nseq, color='#16A085', edgecolor='black', linewidth=1, alpha=0.85, zorder=3)
    ax_b.set_xticks(xpos); ax_b.set_xticklabels(persons, rotation=45, fontsize=9)
    ax_b.set_ylabel('Sequences per participant', fontsize=12, fontweight='bold')
    ax_b.set_xlabel('Participant (LOPO test fold)', fontsize=11)
    ax_b.grid(axis='y', zorder=0); ax_b.set_axisbelow(True)
    ax_b.text(0.97, 0.95, 'Each participant =\none LOPO test fold',
              transform=ax_b.transAxes, ha='right', va='top', fontsize=9.5, style='italic',
              bbox=dict(boxstyle='round', facecolor='#E8F8F5', edgecolor='#16A085', alpha=0.9))

    # (c) sigma distribution per class, thresholds 37 and 50
    sig_fix = dfs[dfs.label==0]['sigma']
    sig_sac = dfs[dfs.label==1]['sigma']
    sig_sp  = dfs[dfs.label==2]['sigma']
    bins = np.linspace(0, 90, 70)
    ax_c.hist(sig_fix, bins=bins, color=C_FIX, alpha=0.65, label='Fixation', edgecolor='none', zorder=3)
    ax_c.hist(sig_sp,  bins=bins, color=C_SP,  alpha=0.65, label='Smooth Pursuit', edgecolor='none', zorder=3)
    ax_c.hist(sig_sac, bins=bins, color=C_SAC, alpha=0.65, label='Saccade', edgecolor='none', zorder=3)
    ax_c.axvline(37, color='black', linestyle='--', linewidth=1.8, zorder=4)
    ax_c.axvline(50, color='black', linestyle='--', linewidth=1.8, zorder=4)
    ax_c.text(37, ax_c.get_ylim()[1]*0.92, r' $\sigma$=37', fontsize=9.5, fontweight='bold')
    ax_c.text(50, ax_c.get_ylim()[1]*0.92, r' $\sigma$=50', fontsize=9.5, fontweight='bold')
    ax_c.set_xlabel(r'Gaze-magnitude standard deviation ($\sigma$)', fontsize=12, fontweight='bold')
    ax_c.set_ylabel('Count (sampled)', fontsize=12, fontweight='bold')
    ax_c.set_xlim(0, 90); ax_c.legend(fontsize=10, loc='upper right')
    ax_c.grid(axis='y', zorder=0); ax_c.set_axisbelow(True)

    # (d) per-participant class composition (stacked)
    fix = dfp['Fixation'].values; sac = dfp['Saccade'].values; sp = dfp['SmoothPursuit'].values
    ax_d.bar(xpos, fix, color=C_FIX, edgecolor='black', linewidth=0.5, label='Fixation', zorder=3)
    ax_d.bar(xpos, sp,  bottom=fix, color=C_SP, edgecolor='black', linewidth=0.5, label='Smooth Pursuit', zorder=3)
    ax_d.bar(xpos, sac, bottom=fix+sp, color=C_SAC, edgecolor='black', linewidth=0.5, label='Saccade', zorder=3)
    ax_d.set_xticks(xpos); ax_d.set_xticklabels(persons, rotation=45, fontsize=9)
    ax_d.set_ylabel('Sequences (stacked by class)', fontsize=12, fontweight='bold')
    ax_d.set_xlabel('Participant', fontsize=11)
    ax_d.legend(fontsize=9.5, loc='upper right')
    ax_d.grid(axis='y', zorder=0); ax_d.set_axisbelow(True)

    for ax, letter in zip([ax_a, ax_b, ax_c, ax_d], ['(a)','(b)','(c)','(d)']):
        ax.text(0.5, -0.16, letter, transform=ax.transAxes, fontsize=15,
                fontweight='bold', ha='center', va='top')

    plt.tight_layout(); plt.subplots_adjust(bottom=0.10, hspace=0.38, wspace=0.22)
    _save('Figure01'); plt.close()


# ============================================================================
# Figure 2 (Figure02.png): model architecture schematic
# ============================================================================
def make_figure02():
    plt.rcParams.update({'figure.facecolor':'white','savefig.facecolor':'white',
                         'font.family':'DejaVu Sans'})
    fig, ax = plt.subplots(figsize=(15, 8.5))
    ax.set_xlim(0, 15); ax.set_ylim(0, 9); ax.axis('off')

    C_INPUT, C_CNN, C_LSTM, C_OUT = '#D5F5E3', '#D6EAF8', '#E8DAEF', '#FCF3CF'
    EDGE = {'input':'#27AE60','cnn':'#2E86C1','lstm':'#8E44AD','out':'#B7950B'}

    def block(x, y, w, h, text, fc, ec, fs=10, bold_first=True):
        ax.add_patch(FancyBboxPatch((x, y), w, h,
            boxstyle="round,pad=0.04,rounding_size=0.12",
            facecolor=fc, edgecolor=ec, linewidth=2, zorder=3))
        lines = text.split('\n'); n = len(lines)
        for i, line in enumerate(lines):
            yy = y + h - 0.32 - i*(h-0.5)/max(n,1) if n>1 else y+h/2
            weight = 'bold' if (i==0 and bold_first) else 'normal'
            size = fs if i==0 else fs-1.5
            ax.text(x+w/2, yy, line, ha='center', va='center',
                    fontsize=size, fontweight=weight, zorder=4)

    def arrow(x1, y1, x2, y2):
        ax.add_patch(FancyArrowPatch((x1,y1),(x2,y2), arrowstyle='-|>',
            mutation_scale=20, color='#444', linewidth=2, zorder=2))

    stages = [(0.3,'INPUT'), (4.0,'TEMPORAL FEATURE\nEXTRACTION (1D-CNN)'),
              (8.0,'SEQUENCE MODELING\n(LSTM)'), (12.0,'CLASSIFICATION')]
    for x, t in stages:
        ax.text(x+1.3, 8.6, t, ha='center', va='center', fontsize=11.5, fontweight='bold')

    block(0.3, 5.2, 2.6, 2.6,
          "Input Layer\n\n(B, 10, 3)\n\n10 frames x\n3D gaze vector\n\n30 Hz, 333 ms",
          C_INPUT, EDGE['input'], fs=11)

    block(4.0, 6.4, 2.6, 1.5, "Conv1D (64)\nkernel=3, ReLU\n(B,10,64)", C_CNN, EDGE['cnn'])
    block(4.0, 5.5, 2.6, 0.7, "BatchNorm + Dropout(0.2)", C_CNN, EDGE['cnn'], fs=8.5, bold_first=False)
    block(4.0, 3.9, 2.6, 1.5, "Conv1D (128)\nkernel=3, ReLU\n(B,10,128)", C_CNN, EDGE['cnn'])
    block(4.0, 3.0, 2.6, 0.7, "BatchNorm + Dropout(0.2)", C_CNN, EDGE['cnn'], fs=8.5, bold_first=False)
    ax.text(5.3, 2.5, 'Params: 25,280', ha='center', fontsize=9.5, color=EDGE['cnn'], fontweight='bold')

    block(8.0, 6.4, 2.6, 1.5, "LSTM (128)\nreturn_seq=True\n(B,10,128)", C_LSTM, EDGE['lstm'])
    block(8.0, 5.5, 2.6, 0.7, "Dropout(0.3)", C_LSTM, EDGE['lstm'], fs=8.5, bold_first=False)
    block(8.0, 3.9, 2.6, 1.5, "LSTM (64)\nreturn_seq=False\n(B,64)", C_LSTM, EDGE['lstm'])
    block(8.0, 3.0, 2.6, 0.7, "Dropout(0.3)", C_LSTM, EDGE['lstm'], fs=8.5, bold_first=False)
    ax.text(9.3, 2.5, 'Params: 137,408', ha='center', fontsize=9.5, color=EDGE['lstm'], fontweight='bold')

    block(12.0, 6.4, 2.6, 1.5, "Dense (128)\nReLU\n(B,128)", C_OUT, EDGE['out'])
    block(12.0, 5.5, 2.6, 0.7, "Dropout(0.4)", C_OUT, EDGE['out'], fs=8.5, bold_first=False)
    block(12.0, 3.9, 2.6, 1.5, "Dense (3)\nSoftmax\n(B,3)", C_OUT, EDGE['out'])
    block(12.0, 2.7, 2.6, 1.0, "Output classes:\nFixation / Saccade /\nSmooth Pursuit",
          C_OUT, EDGE['out'], fs=8.5, bold_first=False)
    ax.text(13.3, 2.2, 'Params: 8,707', ha='center', fontsize=9.5, color=EDGE['out'], fontweight='bold')

    arrow(2.9, 6.5, 4.0, 6.5); arrow(6.6, 5.5, 8.0, 5.5); arrow(10.6, 5.5, 12.0, 5.5)
    for x in (5.3, 9.3, 13.3):
        arrow(x, 6.4, x, 6.2); arrow(x, 5.5, x, 5.4)

    info = ("Total trainable parameters: 215,811   |   Optimizer: Adam (lr = 0.001)   |   "
            "Loss: Sparse Categorical Crossentropy   |   Batch: 128   |   Epochs: 30\n"
            "Evaluation: Leave-One-Person-Out (LOPO) 15-fold cross-validation - "
            "train on 14 participants, test on 1 held-out participant (no participant overlap)")
    ax.text(7.5, 1.2, info, ha='center', va='center', fontsize=9.5,
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#F8F9F9', edgecolor='#566573', linewidth=1.3))

    handles = [mpatches.Patch(facecolor=C_INPUT, edgecolor=EDGE['input'], label='Input'),
               mpatches.Patch(facecolor=C_CNN, edgecolor=EDGE['cnn'], label='1D-CNN'),
               mpatches.Patch(facecolor=C_LSTM, edgecolor=EDGE['lstm'], label='LSTM'),
               mpatches.Patch(facecolor=C_OUT, edgecolor=EDGE['out'], label='Classification')]
    ax.legend(handles=handles, loc='upper center', ncol=4, fontsize=10,
              bbox_to_anchor=(0.5, 0.32), frameon=True)

    plt.tight_layout(); _save('Figure02'); plt.close()


# ============================================================================
# Figure 4 (Figure04.png): aggregated confusion matrix, two panels
# ============================================================================
def make_figure04():
    plt.rcParams.update({'figure.facecolor':'white','axes.facecolor':'white',
                         'savefig.facecolor':'white','font.family':'DejaVu Sans'})
    cm = load_confusion()
    classes = ['Fixation', 'Saccade', 'Smooth\nPursuit']
    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(15, 6.2))

    # (a) raw counts
    im_a = ax_a.imshow(cm, cmap='Blues', aspect='auto')
    ax_a.set_xticks(range(3)); ax_a.set_yticks(range(3))
    ax_a.set_xticklabels(classes, fontsize=11); ax_a.set_yticklabels(classes, fontsize=11)
    ax_a.set_xlabel('Predicted', fontsize=13, fontweight='bold')
    ax_a.set_ylabel('True', fontsize=13, fontweight='bold')
    thr = cm.max()/2
    for i in range(3):
        for j in range(3):
            ax_a.text(j, i, f'{cm[i,j]:,}', ha='center', va='center',
                      color='white' if cm[i,j] > thr else 'black', fontsize=13, fontweight='bold')
    plt.colorbar(im_a, ax=ax_a, fraction=0.046, pad=0.04).set_label('Count', fontsize=11)

    # (b) row-normalized recall
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True) * 100
    im_b = ax_b.imshow(cm_norm, cmap='RdYlGn', aspect='auto', vmin=0, vmax=100)
    ax_b.set_xticks(range(3)); ax_b.set_yticks(range(3))
    ax_b.set_xticklabels(classes, fontsize=11); ax_b.set_yticklabels(classes, fontsize=11)
    ax_b.set_xlabel('Predicted', fontsize=13, fontweight='bold')
    ax_b.set_ylabel('True', fontsize=13, fontweight='bold')
    for i in range(3):
        for j in range(3):
            ax_b.text(j, i, f'{cm_norm[i,j]:.1f}%', ha='center', va='center',
                      color='black', fontsize=13, fontweight='bold')
    plt.colorbar(im_b, ax=ax_b, fraction=0.046, pad=0.04).set_label('Recall (%)', fontsize=11)

    for ax, letter in zip([ax_a, ax_b], ['(a)','(b)']):
        ax.text(0.5, -0.18, letter, transform=ax.transAxes, fontsize=15,
                fontweight='bold', ha='center', va='top')

    plt.tight_layout(); plt.subplots_adjust(bottom=0.16, wspace=0.30)
    _save('Figure04'); plt.close()


# ============================================================================
# Figure 5 (Figure05.png): training dynamics for a representative fold (p11)
# ============================================================================
def make_figure05():
    plt.rcParams.update(BASE_RC)
    df = pd.read_csv(RESULTS / 'fig4_training_history.csv')
    ep = df['epoch'].values
    C_TRAIN, C_VAL = '#2E86C1', '#E67E22'
    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(15, 6))

    # (a) loss
    ax_a.plot(ep, df['train_loss'], '-o', color=C_TRAIN, linewidth=2.2, markersize=4,
              label='Training loss', zorder=3)
    ax_a.plot(ep, df['val_loss'], '-s', color=C_VAL, linewidth=2.2, markersize=4,
              label='Validation loss', zorder=3)
    imin = df['val_loss'].idxmin()
    ax_a.scatter([ep[imin]], [df['val_loss'].iloc[imin]], s=120, facecolor='none',
                 edgecolor='#C0392B', linewidth=2, zorder=5)
    ax_a.annotate(f'min val loss\n(epoch {ep[imin]}: {df["val_loss"].iloc[imin]:.3f})',
                  xy=(ep[imin], df['val_loss'].iloc[imin]),
                  xytext=(ep[imin]+3, df['val_loss'].iloc[imin]+0.05),
                  fontsize=9, color='#C0392B', fontweight='bold',
                  arrowprops=dict(arrowstyle='->', color='#C0392B', lw=1.2))
    ax_a.set_xlabel('Epoch', fontsize=13, fontweight='bold')
    ax_a.set_ylabel('Loss (Sparse Categorical Crossentropy)', fontsize=12, fontweight='bold')
    ax_a.set_xlim(0, 31); ax_a.legend(fontsize=11, loc='upper right')
    ax_a.grid(True, zorder=0); ax_a.set_axisbelow(True)

    # (b) accuracy
    ax_b.plot(ep, df['train_acc']*100, '-o', color=C_TRAIN, linewidth=2.2, markersize=4,
              label='Training accuracy', zorder=3)
    ax_b.plot(ep, df['val_acc']*100, '-s', color=C_VAL, linewidth=2.2, markersize=4,
              label='Validation accuracy', zorder=3)
    imax = df['val_acc'].idxmax()
    ax_b.scatter([ep[imax]], [df['val_acc'].iloc[imax]*100], s=120, facecolor='none',
                 edgecolor='#27AE60', linewidth=2, zorder=5)
    ax_b.annotate(f'peak val acc\n(epoch {ep[imax]}: {df["val_acc"].iloc[imax]*100:.1f}%)',
                  xy=(ep[imax], df['val_acc'].iloc[imax]*100),
                  xytext=(ep[imax]-1, df['val_acc'].iloc[imax]*100-5),
                  fontsize=9, color='#1E8449', fontweight='bold',
                  arrowprops=dict(arrowstyle='->', color='#27AE60', lw=1.2))
    ax_b.set_xlabel('Epoch', fontsize=13, fontweight='bold')
    ax_b.set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
    ax_b.set_xlim(0, 31); ax_b.set_ylim(78, 95)
    ax_b.legend(fontsize=11, loc='lower right')
    ax_b.grid(True, zorder=0); ax_b.set_axisbelow(True)

    for ax, l in zip([ax_a, ax_b], ['(a)','(b)']):
        ax.text(0.5, -0.16, l, transform=ax.transAxes, fontsize=15,
                fontweight='bold', ha='center', va='top')

    plt.tight_layout(); plt.subplots_adjust(bottom=0.16, wspace=0.22)
    _save('Figure05', png_only=True); plt.close()


# ============================================================================
# Figure 6 (Figure06.png): ablation study, four panels
# ============================================================================
def make_figure06():
    plt.rcParams.update(BASE_RC)
    persons, cnn, lstm, hyb = load_fold_results()
    macro = [cnn.mean(), lstm.mean(), hyb.mean()]
    sd    = [cnn.std(ddof=1), lstm.std(ddof=1), hyb.std(ddof=1)]
    n = 15
    ci = [1.96*s/np.sqrt(n) for s in sd]
    models = ['CNN','LSTM','CNN+LSTM']
    C = C_MODEL
    fig, axes = plt.subplots(2, 2, figsize=(14, 11))
    ax_a, ax_b, ax_c, ax_d = axes[0,0], axes[0,1], axes[1,0], axes[1,1]

    # (a) mean accuracy + SD
    ax_a.bar(models, macro, yerr=sd, capsize=6, color=C, edgecolor='black',
             linewidth=1.5, alpha=0.85, width=0.6, zorder=3,
             error_kw=dict(linewidth=2, ecolor='#333'))
    for i,(m,s) in enumerate(zip(macro,sd)):
        ax_a.text(i, m+s+0.6, f'{m:.2f}%\n(\u00b1{s:.2f})', ha='center', fontweight='bold', fontsize=10)
    ax_a.set_ylabel('Mean LOPO Accuracy (%)', fontsize=12, fontweight='bold')
    ax_a.set_ylim(70, 95); ax_a.grid(axis='y', zorder=0); ax_a.set_axisbelow(True)
    ax_a.tick_params(labelsize=11)

    # (b) 95% CI
    xpos = [0,1,2]
    for x,m,c,civ in zip(xpos,macro,C,ci):
        ax_b.errorbar(x, m, yerr=civ, fmt='o', markersize=12, capsize=7, capthick=2.5,
                      color=c, ecolor='black', markeredgecolor='black',
                      markeredgewidth=1.3, linewidth=2.5, zorder=3)
        ax_b.text(x, m+civ+0.5, f'[{m-civ:.2f},\n{m+civ:.2f}]', ha='center', fontsize=9, fontweight='bold')
    ax_b.set_xticks(xpos); ax_b.set_xticklabels(models, fontsize=11)
    ax_b.set_ylabel('Accuracy (%) with 95% CI', fontsize=12, fontweight='bold')
    ax_b.set_ylim(75, 93); ax_b.set_xlim(-0.5, 2.5)
    ax_b.grid(axis='y', zorder=0); ax_b.set_axisbelow(True)

    # (c) per-fold accuracy
    x = np.arange(len(persons))
    ax_c.plot(x, cnn, 'o-', color=C[0], label='CNN', linewidth=1.8, markersize=5, zorder=3)
    ax_c.plot(x, lstm,'s-', color=C[1], label='LSTM', linewidth=1.8, markersize=5, zorder=3)
    ax_c.plot(x, hyb, '^-', color=C[2], label='CNN+LSTM', linewidth=2.2, markersize=6, zorder=4)
    ax_c.set_xticks(x); ax_c.set_xticklabels(persons, rotation=45, fontsize=8.5)
    ax_c.set_xlabel('Held-out participant (LOPO fold)', fontsize=11, fontweight='bold')
    ax_c.set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
    ax_c.set_ylim(45, 97); ax_c.legend(fontsize=10, loc='lower left', ncol=3)
    ax_c.grid(True, zorder=0); ax_c.set_axisbelow(True)
    ax_c.annotate('LSTM unstable\n(p00: 51.9%)', xy=(0,51.89), xytext=(2.2,55),
                  fontsize=8.5, color=C[1], fontweight='bold',
                  arrowprops=dict(arrowstyle='->', color=C[1], lw=1.3))

    # (d) statistical summary
    ax_d.axis('off'); ax_d.set_xlim(0,10); ax_d.set_ylim(0,10)
    rows = [
        ("McNemar's Test", "", "", True),
        ("  CNN vs CNN+LSTM", r"$\chi^2$ = 3676.60", "p < 0.001 ***", False),
        ("  LSTM vs CNN+LSTM", r"$\chi^2$ = 6831.96", "p < 0.001 ***", False),
        ("Friedman's Test", r"$\chi^2_F$ = 10.80", "p = 0.0045 **", True),
        ("Cohen's d (fold-level)", "", "", True),
        ("  CNN+LSTM vs CNN", "d = 1.02", "large", False),
        ("  CNN+LSTM vs LSTM", "d = 0.58", "medium", False),
    ]
    y = 9.2
    for label,val,sig,hdr in rows:
        w = 'bold' if hdr else 'normal'; col = '#1A5276' if hdr else '#2C3E50'
        ax_d.text(0.2, y, label, fontsize=12 if hdr else 11, fontweight=w, color=col, va='center')
        if val: ax_d.text(5.0, y, val, fontsize=11, va='center', fontweight='bold')
        if sig:
            sc = '#C0392B' if '*' in sig else '#117A30'
            ax_d.text(7.8, y, sig, fontsize=10, va='center', color=sc, fontweight='bold')
        y -= 1.28
    ax_d.text(5, 0.2,
              "CNN+LSTM is significantly more accurate AND more stable\n"
              "across participants than either single-modality model.",
              fontsize=9.5, ha='center', va='bottom', style='italic',
              bbox=dict(boxstyle='round', facecolor='#FCF3CF', alpha=0.9,
                        edgecolor='#9A7D0A', linewidth=1.3))

    for ax, l in zip([ax_a, ax_b, ax_c, ax_d], ['(a)','(b)','(c)','(d)']):
        ax.text(0.5, -0.16, l, transform=ax.transAxes, fontsize=15,
                fontweight='bold', ha='center', va='top')

    plt.tight_layout(); plt.subplots_adjust(bottom=0.10, hspace=0.34, wspace=0.24)
    _save('Figure06'); plt.close()


# ============================================================================
# Figure 7 (Figure07.png): per-fold distribution, two panels
# ============================================================================
def make_figure07():
    plt.rcParams.update(BASE_RC)
    persons, cnn, lstm, hyb = load_fold_results()
    C = C_MODEL
    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(15, 6.4))

    # (a) violin + box
    data = [cnn, lstm, hyb]; labels = ['CNN','LSTM','CNN+LSTM']
    parts = ax_a.violinplot(data, positions=[0,1,2], widths=0.7,
                            showmeans=False, showmedians=False, showextrema=False)
    for pc, c in zip(parts['bodies'], C):
        pc.set_facecolor(c); pc.set_alpha(0.35); pc.set_edgecolor(c); pc.set_linewidth(1.5)
    bp = ax_a.boxplot(data, positions=[0,1,2], widths=0.25, patch_artist=True, showfliers=True,
                      medianprops=dict(color='black', linewidth=2),
                      whiskerprops=dict(color='#333', linewidth=1.5),
                      capprops=dict(color='#333', linewidth=1.5),
                      flierprops=dict(marker='o', markerfacecolor='red', markersize=6, alpha=0.7))
    for patch, c in zip(bp['boxes'], C):
        patch.set_facecolor(c); patch.set_alpha(0.75); patch.set_edgecolor('black'); patch.set_linewidth(1.3)
    np.random.seed(1)
    for i, d in enumerate(data):
        ax_a.scatter(np.random.normal(i, 0.04, len(d)), d, s=22, color='black', alpha=0.45, zorder=5)
    ax_a.set_xticks([0,1,2]); ax_a.set_xticklabels(labels, fontsize=11)
    ax_a.set_ylabel('Per-fold Accuracy (%)', fontsize=12, fontweight='bold')
    ax_a.set_ylim(45, 98); ax_a.grid(axis='y', zorder=0); ax_a.set_axisbelow(True)
    for i, d in enumerate(data):
        ax_a.text(i, 47, f'SD={d.std(ddof=1):.2f}', ha='center', fontsize=9.5,
                  fontweight='bold', color=C[i])
    ax_a.annotate('p00', xy=(1, 51.89), xytext=(1.35, 54), fontsize=9, color=C[1],
                  fontweight='bold', arrowprops=dict(arrowstyle='->', color=C[1], lw=1.2))

    # (b) per-participant advantage of the hybrid
    best_single = np.maximum(cnn, lstm)
    gain = hyb - best_single
    order = np.argsort(gain)
    colors_g = ['#C0392B' if g < 0 else '#27AE60' for g in gain[order]]
    ypos = np.arange(len(persons))
    ax_b.barh(ypos, gain[order], color=colors_g, edgecolor='black', linewidth=1, alpha=0.85, zorder=3)
    ax_b.set_yticks(ypos); ax_b.set_yticklabels([persons[i] for i in order], fontsize=9.5)
    ax_b.axvline(0, color='black', linewidth=1.5, zorder=4)
    ax_b.set_xlabel('CNN+LSTM advantage over best single model (pp)', fontsize=11.5, fontweight='bold')
    ax_b.set_ylabel('Participant', fontsize=12, fontweight='bold')
    ax_b.grid(axis='x', zorder=0); ax_b.set_axisbelow(True)
    for i, g in enumerate(gain[order]):
        ax_b.text(g + (0.15 if g>=0 else -0.15), i, f'{g:+.1f}',
                  va='center', ha='left' if g>=0 else 'right', fontsize=8.5, fontweight='bold')
    n_pos = int(np.sum(gain >= 0))
    ax_b.text(0.97, 0.04, f'Hybrid best in {n_pos}/15 folds\nMean advantage: {gain.mean():+.2f} pp',
              transform=ax_b.transAxes, ha='right', va='bottom', fontsize=9.5, fontweight='bold',
              bbox=dict(boxstyle='round', facecolor='#E8F8F5', edgecolor='#27AE60', alpha=0.9))

    for ax, l in zip([ax_a, ax_b], ['(a)','(b)']):
        ax.text(0.5, -0.16, l, transform=ax.transAxes, fontsize=15,
                fontweight='bold', ha='center', va='top')

    plt.tight_layout(); plt.subplots_adjust(bottom=0.16, wspace=0.28)
    _save('Figure07'); plt.close()


if __name__ == '__main__':
    print('Generating figures...')
    make_figure01()
    make_figure02()
    make_figure04()
    make_figure05()
    make_figure06()
    make_figure07()
    print('Done. Note: Figure03 (label-generation schematic, paper Figure 2) '
          'is a separate vector graphic and is not produced by this script.')
